from __future__ import annotations

import json
import shutil
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "extension"
DIST_DIR = ROOT / "dist"
UNPACKED_DIR = DIST_DIR / "chatgpt-formula-copy-chrome"
USERSCRIPT_PATH = ROOT / "chatgpt-latex-copy.user.js"


def userscript_body(source: str) -> str:
    end_marker = "// ==/UserScript=="
    marker_index = source.find(end_marker)
    if marker_index == -1:
        raise RuntimeError("Userscript metadata block is missing")
    return source[marker_index + len(end_marker) :].lstrip()


def build_content_script(source: str) -> str:
    body = userscript_body(source)
    return f'''// Generated from chatgpt-latex-copy.user.js. Do not edit this file directly.
(() => {{
  "use strict";

  const defaults = {{ copyFormat: "smart", selectionCopyEnabled: true }};
  chrome.storage.local.get(defaults, (stored) => {{
    const cache = {{ ...defaults, ...stored }};
    globalThis.GM_getValue = (key, fallback) =>
      Object.prototype.hasOwnProperty.call(cache, key) ? cache[key] : fallback;
    globalThis.GM_setValue = (key, value) => {{
      cache[key] = value;
      chrome.storage.local.set({{ [key]: value }});
    }};

{body}
  }});
}})();
'''


def validate_manifest(manifest: dict, package_version: str) -> None:
    if manifest.get("manifest_version") != 3:
        raise RuntimeError("Chrome Web Store package must use Manifest V3")
    if manifest.get("version") != package_version:
        raise RuntimeError(
            f"manifest version {manifest.get('version')} does not match package version {package_version}"
        )
    if manifest.get("permissions") != ["storage"]:
        raise RuntimeError("Unexpected permissions: keep the extension at minimum permission")


def main() -> None:
    package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
    manifest = json.loads((SOURCE_DIR / "manifest.json").read_text(encoding="utf-8"))
    validate_manifest(manifest, package["version"])

    expected_icons = [SOURCE_DIR / "icons" / f"icon-{size}.png" for size in (16, 32, 48, 128)]
    missing_icons = [str(path) for path in expected_icons if not path.exists()]
    if missing_icons:
        raise RuntimeError(f"Missing extension icons: {missing_icons}")

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    resolved_unpacked = UNPACKED_DIR.resolve()
    if resolved_unpacked.parent != DIST_DIR.resolve():
        raise RuntimeError("Refusing to replace a directory outside dist")
    if UNPACKED_DIR.exists():
        shutil.rmtree(UNPACKED_DIR)
    shutil.copytree(SOURCE_DIR, UNPACKED_DIR)

    content = build_content_script(USERSCRIPT_PATH.read_text(encoding="utf-8"))
    (UNPACKED_DIR / "content.js").write_text(content, encoding="utf-8", newline="\n")

    zip_path = DIST_DIR / f"chatgpt-formula-copy-chrome-v{package['version']}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(UNPACKED_DIR.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(UNPACKED_DIR).as_posix())

    with zipfile.ZipFile(zip_path) as archive:
        names = archive.namelist()
        if "manifest.json" not in names or any(name.startswith("chatgpt-formula-copy-chrome/") for name in names):
            raise RuntimeError("ZIP root is invalid: manifest.json must be at archive root")
        if archive.testzip() is not None:
            raise RuntimeError("ZIP integrity check failed")

    print(zip_path)


if __name__ == "__main__":
    main()

