from __future__ import annotations

import json
import shutil
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "extension"
DIST_DIR = ROOT / "dist"
UNPACKED_DIR = DIST_DIR / "chatgpt-formula-copy-chrome"
USERSCRIPT_PATH = ROOT / "chatgpt-latex-copy.user.js"
CHATGPT_MATCHES = [
    "https://chatgpt.com/*",
    "https://*.chatgpt.com/*",
    "https://chat.openai.com/*",
]
PACKAGE_FILES = [
    "manifest.json",
    "popup.html",
    "popup.css",
    "popup.js",
    "_locales/en/messages.json",
    "_locales/zh_CN/messages.json",
    "icons/icon-16.png",
    "icons/icon-32.png",
    "icons/icon-48.png",
    "icons/icon-128.png",
]


def userscript_body(source: str) -> str:
    end_marker = "// ==/UserScript=="
    marker_index = source.find(end_marker)
    if marker_index == -1:
        raise RuntimeError("Userscript metadata block is missing")
    return source[marker_index + len(end_marker) :].lstrip()


def build_content_script(source: str) -> str:
    body = userscript_body(source)
    return f'''// Generated from chatgpt-latex-copy.user.js. Do not edit this file directly.
(() => {{
  "use strict";

  const defaults = {{
    copyFormat: "smart",
    copyEnabled: true,
    selectionCopyEnabled: true,
    exportMetadataEnabled: true,
    welcomeShown: false
  }};
  const pendingMessages = [];
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {{
    if (!message || typeof message !== "object") return undefined;
    if (
      message.type !== "GPT_FORMULA_COPY_STATUS" &&
      message.type !== "GPT_FORMULA_COPY_OPEN_PANEL"
    ) return undefined;

    const respond = (api) => {{
      if (!api) {{
        sendResponse({{ ok: false, error: "not_ready" }});
      }} else if (message.type === "GPT_FORMULA_COPY_STATUS") {{
        sendResponse(api.getStatus());
      }} else {{
        const opened = api.openControlPanel(message.tab || "copy");
        sendResponse({{ ok: opened !== false }});
      }}
    }};

    const api = globalThis.__GPT_LATEX_COPY_API__;
    if (api) {{
      respond(api);
      return undefined;
    }}
    pendingMessages.push(respond);
    return true;
  }});

  chrome.storage.local.get(defaults, (stored) => {{
    const cache = {{ ...defaults, ...stored }};
    globalThis.GM_getValue = (key, fallback) =>
      Object.prototype.hasOwnProperty.call(cache, key) ? cache[key] : fallback;
    globalThis.GM_setValue = (key, value) => {{
      cache[key] = value;
      chrome.storage.local.set({{ [key]: value }});
    }};

{body}
    const api = globalThis.__GPT_LATEX_COPY_API__;
    for (const respond of pendingMessages.splice(0)) respond(api);
  }});
}})();
'''


def validate_manifest(manifest: dict, package_version: str) -> None:
    if manifest.get("manifest_version") != 3:
        raise RuntimeError("Chrome Web Store package must use Manifest V3")
    if manifest.get("version") != package_version:
        raise RuntimeError(
            f"manifest version {manifest.get('version')} does not match package version {package_version}"
        )
    if manifest.get("permissions") != ["storage"]:
        raise RuntimeError("Unexpected permissions: keep the extension at minimum permission")
    for key in (
        "host_permissions",
        "optional_permissions",
        "optional_host_permissions",
        "externally_connectable",
    ):
        if manifest.get(key):
            raise RuntimeError(f"Unexpected {key}: keep the extension at minimum permission")
    content_scripts = manifest.get("content_scripts")
    expected_content_scripts = [
        {
            "matches": CHATGPT_MATCHES,
            "js": ["content.js"],
            "run_at": "document_start",
        }
    ]
    if content_scripts != expected_content_scripts:
        raise RuntimeError("Unexpected content_scripts: keep the ChatGPT-only allowlist")


def main() -> None:
    package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
    manifest = json.loads((SOURCE_DIR / "manifest.json").read_text(encoding="utf-8"))
    validate_manifest(manifest, package["version"])

    expected_icons = [SOURCE_DIR / "icons" / f"icon-{size}.png" for size in (16, 32, 48, 128)]
    missing_icons = [str(path) for path in expected_icons if not path.exists()]
    if missing_icons:
        raise RuntimeError(f"Missing extension icons: {missing_icons}")

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    resolved_unpacked = UNPACKED_DIR.resolve()
    if resolved_unpacked.parent != DIST_DIR.resolve():
        raise RuntimeError("Refusing to replace a directory outside dist")
    if UNPACKED_DIR.exists():
        shutil.rmtree(UNPACKED_DIR)
    UNPACKED_DIR.mkdir(parents=True)
    for relative_name in PACKAGE_FILES:
        source_path = SOURCE_DIR / relative_name
        if not source_path.is_file():
            raise RuntimeError(f"Missing package file: {source_path}")
        destination_path = UNPACKED_DIR / relative_name
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, destination_path)

    content = build_content_script(USERSCRIPT_PATH.read_text(encoding="utf-8"))
    (UNPACKED_DIR / "content.js").write_text(content, encoding="utf-8", newline="\n")

    zip_path = DIST_DIR / f"chatgpt-formula-copy-chrome-v{package['version']}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(UNPACKED_DIR.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(UNPACKED_DIR).as_posix())

    with zipfile.ZipFile(zip_path) as archive:
        names = archive.namelist()
        if "manifest.json" not in names or any(name.startswith("chatgpt-formula-copy-chrome/") for name in names):
            raise RuntimeError("ZIP root is invalid: manifest.json must be at archive root")
        if archive.testzip() is not None:
            raise RuntimeError("ZIP integrity check failed")

    print(zip_path)


if __name__ == "__main__":
    main()
